import './globals.css'
import 'react-toastify/dist/ReactToastify.css';
import type { Metadata } from 'next'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Providers from './provider'
import ToastNotify from './components/ToastNotify'
import UserInitializer from './components/UserInitializer';
import { roboto } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
        <UserInitializer/>
      <div className="min-h-screen bg-base-300 flex flex-col">
          <Navbar />
          <div className="flex-grow">{children}</div>
          <Footer />
        </div>
        <ToastNotify />
        </Providers>
        </body>
    </html>
  )
}
